export const ROLES = {
  CITIZEN: "CITIZEN",
  OFFICER: "OFFICER",
  SUPERVISOR: "SUPERVISOR",
  ADMIN: "ADMIN",
};

export const OTP_PURPOSE = {
  LOGIN: "LOGIN",
  RESET_PASSWORD: "RESET_PASSWORD",
};

export const COMPLAINT_STATES = {
  CREATED: "CREATED",
  ASSIGNED: "ASSIGNED",
  IN_PROGRESS: "IN_PROGRESS",
  PENDING_VERIFICATION: "PENDING_VERIFICATION", // NEW
  RESOLVED: "RESOLVED",
  REJECTED: "REJECTED",
  WITHDRAWN: "WITHDRAWN",
};
